// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMFBXzGA8vBjqksKrUihlB7FXez17Xzw0',
    appId: '1:642446362685:android:96322c7c543e430d308254',
    messagingSenderId: '642446362685',
    projectId: 'keisan-4bf8e',
    storageBucket: 'keisan-4bf8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpZQouJPp5-QY83W032arDPBPKkXCQU_4',
    appId: '1:642446362685:ios:fc23812671502d68308254',
    messagingSenderId: '642446362685',
    projectId: 'keisan-4bf8e',
    storageBucket: 'keisan-4bf8e.firebasestorage.app',
    androidClientId: '642446362685-0meg2591d9jla6nfb0qlqfuhokt23v3c.apps.googleusercontent.com',
    iosClientId: '642446362685-33048i9hjvjpttcp7qkp2vsu5t6gs1hl.apps.googleusercontent.com',
    iosBundleId: 'com.keisan.app',
  );

}